/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as AvvRouteImport } from './routes/avv'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSubscribeRouteImport } from './routes/_authenticated/subscribe'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRecipesRouteImport } from './routes/_authenticated/recipes'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedContactRouteImport } from './routes/_authenticated/contact'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedAccountBillingRouteImport } from './routes/_authenticated/account.billing'
import { Route as AuthenticatedClientsClientIdIndexRouteImport } from './routes/_authenticated/clients.$clientId.index'
import { Route as AuthenticatedClientsClientIdEditRouteImport } from './routes/_authenticated/clients.$clientId.edit'
import { Route as AuthenticatedClientsClientIdRecipesNewRouteImport } from './routes/_authenticated/clients.$clientId.recipes.new'
import { Route as AuthenticatedClientsClientIdRecipesRecipeIdRouteImport } from './routes/_authenticated/clients.$clientId.recipes.$recipeId'

const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const AvvRoute = AvvRouteImport.update({
  id: '/avv',
  path: '/avv',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubscribeRoute = AuthenticatedSubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecipesRoute = AuthenticatedRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactRoute = AuthenticatedContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const AuthenticatedAccountBillingRoute =
  AuthenticatedAccountBillingRouteImport.update({
    id: '/account/billing',
    path: '/account/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsClientIdIndexRoute =
  AuthenticatedClientsClientIdIndexRouteImport.update({
    id: '/$clientId/',
    path: '/$clientId/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedClientsClientIdEditRoute =
  AuthenticatedClientsClientIdEditRouteImport.update({
    id: '/$clientId/edit',
    path: '/$clientId/edit',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedClientsClientIdRecipesNewRoute =
  AuthenticatedClientsClientIdRecipesNewRouteImport.update({
    id: '/$clientId/recipes/new',
    path: '/$clientId/recipes/new',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedClientsClientIdRecipesRecipeIdRoute =
  AuthenticatedClientsClientIdRecipesRecipeIdRouteImport.update({
    id: '/$clientId/recipes/$recipeId',
    path: '/$clientId/recipes/$recipeId',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avv': typeof AvvRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/subscribe': typeof AuthenticatedSubscribeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/help': typeof AuthenticatedHelpRoute
  '/contact': typeof AuthenticatedContactRoute
  '/account/billing': typeof AuthenticatedAccountBillingRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/clients/$clientId/': typeof AuthenticatedClientsClientIdIndexRoute
  '/clients/$clientId/recipes/$recipeId': typeof AuthenticatedClientsClientIdRecipesRecipeIdRoute
  '/clients/$clientId/recipes/new': typeof AuthenticatedClientsClientIdRecipesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avv': typeof AvvRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/subscribe': typeof AuthenticatedSubscribeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/recipes': typeof AuthenticatedRecipesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/help': typeof AuthenticatedHelpRoute
  '/contact': typeof AuthenticatedContactRoute
  '/account/billing': typeof AuthenticatedAccountBillingRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdIndexRoute
  '/clients/$clientId/recipes/$recipeId': typeof AuthenticatedClientsClientIdRecipesRecipeIdRoute
  '/clients/$clientId/recipes/new': typeof AuthenticatedClientsClientIdRecipesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/avv': typeof AvvRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/subscribe': typeof AuthenticatedSubscribeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/recipes': typeof AuthenticatedRecipesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/contact': typeof AuthenticatedContactRoute
  '/_authenticated/account/billing': typeof AuthenticatedAccountBillingRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/_authenticated/clients/$clientId/': typeof AuthenticatedClientsClientIdIndexRoute
  '/_authenticated/clients/$clientId/recipes/$recipeId': typeof AuthenticatedClientsClientIdRecipesRecipeIdRoute
  '/_authenticated/clients/$clientId/recipes/new': typeof AuthenticatedClientsClientIdRecipesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avv'
    | '/datenschutz'
    | '/impressum'
    | '/clients'
    | '/subscribe'
    | '/settings'
    | '/recipes'
    | '/profile'
    | '/inventory'
    | '/help'
    | '/contact'
    | '/account/billing'
    | '/clients/new'
    | '/api/public/stripe-webhook'
    | '/clients/'
    | '/clients/$clientId/edit'
    | '/clients/$clientId/'
    | '/clients/$clientId/recipes/$recipeId'
    | '/clients/$clientId/recipes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avv'
    | '/datenschutz'
    | '/impressum'
    | '/subscribe'
    | '/settings'
    | '/recipes'
    | '/profile'
    | '/inventory'
    | '/help'
    | '/contact'
    | '/account/billing'
    | '/clients/new'
    | '/api/public/stripe-webhook'
    | '/clients'
    | '/clients/$clientId/edit'
    | '/clients/$clientId'
    | '/clients/$clientId/recipes/$recipeId'
    | '/clients/$clientId/recipes/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/avv'
    | '/datenschutz'
    | '/impressum'
    | '/_authenticated/clients'
    | '/_authenticated/subscribe'
    | '/_authenticated/settings'
    | '/_authenticated/recipes'
    | '/_authenticated/profile'
    | '/_authenticated/inventory'
    | '/_authenticated/help'
    | '/_authenticated/contact'
    | '/_authenticated/account/billing'
    | '/_authenticated/clients/new'
    | '/api/public/stripe-webhook'
    | '/_authenticated/clients/'
    | '/_authenticated/clients/$clientId/edit'
    | '/_authenticated/clients/$clientId/'
    | '/_authenticated/clients/$clientId/recipes/$recipeId'
    | '/_authenticated/clients/$clientId/recipes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvvRoute: typeof AvvRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avv': {
      id: '/avv'
      path: '/avv'
      fullPath: '/avv'
      preLoaderRoute: typeof AvvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/subscribe': {
      id: '/_authenticated/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof AuthenticatedSubscribeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes': {
      id: '/_authenticated/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthenticatedRecipesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contact': {
      id: '/_authenticated/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AuthenticatedContactRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/account/billing': {
      id: '/_authenticated/account/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AuthenticatedAccountBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId/': {
      id: '/_authenticated/clients/$clientId/'
      path: '/$clientId'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof AuthenticatedClientsClientIdIndexRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/clients/$clientId/edit': {
      id: '/_authenticated/clients/$clientId/edit'
      path: '/$clientId/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof AuthenticatedClientsClientIdEditRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/clients/$clientId/recipes/new': {
      id: '/_authenticated/clients/$clientId/recipes/new'
      path: '/$clientId/recipes/new'
      fullPath: '/clients/$clientId/recipes/new'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRecipesNewRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/clients/$clientId/recipes/$recipeId': {
      id: '/_authenticated/clients/$clientId/recipes/$recipeId'
      path: '/$clientId/recipes/$recipeId'
      fullPath: '/clients/$clientId/recipes/$recipeId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRecipesRecipeIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedClientsClientIdEditRoute: typeof AuthenticatedClientsClientIdEditRoute
  AuthenticatedClientsClientIdIndexRoute: typeof AuthenticatedClientsClientIdIndexRoute
  AuthenticatedClientsClientIdRecipesRecipeIdRoute: typeof AuthenticatedClientsClientIdRecipesRecipeIdRoute
  AuthenticatedClientsClientIdRecipesNewRoute: typeof AuthenticatedClientsClientIdRecipesNewRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedClientsClientIdEditRoute: AuthenticatedClientsClientIdEditRoute,
  AuthenticatedClientsClientIdIndexRoute:
    AuthenticatedClientsClientIdIndexRoute,
  AuthenticatedClientsClientIdRecipesRecipeIdRoute:
    AuthenticatedClientsClientIdRecipesRecipeIdRoute,
  AuthenticatedClientsClientIdRecipesNewRoute:
    AuthenticatedClientsClientIdRecipesNewRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedSubscribeRoute: typeof AuthenticatedSubscribeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedRecipesRoute: typeof AuthenticatedRecipesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedContactRoute: typeof AuthenticatedContactRoute
  AuthenticatedAccountBillingRoute: typeof AuthenticatedAccountBillingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedSubscribeRoute: AuthenticatedSubscribeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedRecipesRoute: AuthenticatedRecipesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedContactRoute: AuthenticatedContactRoute,
  AuthenticatedAccountBillingRoute: AuthenticatedAccountBillingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AvvRoute: AvvRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
